# .travis.yml
language: csharp
dist: bionic
dotnet: 2.2.105
mono: none
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
script:
  - dotnet sln remove bench/RelationalLock.Bench
  - dotnet restore
  - dotnet build
  - dotnet test